//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::payment::Entity as Payment;
pub use super::referral_code::Entity as ReferralCode;
pub use super::transfer::Entity as Transfer;
pub use super::user::Entity as User;
